apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: secret-restart-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-restart-controller
subjects:
- kind: ServiceAccount
  name: secret-restart-controller
