apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: secret-restart-controller
rules:
- apiGroups: [""]
  resources: ["secrets", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
