kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: secret-restart-controller
  namespace: 
  labels:
    app: secret-restart-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: secret-restart-controller
    spec:
      serviceAccountName: secret-restart-controller
      containers:
        - name: secret-restart-controller
          image: xtruder/k8s-secret-restart-controller
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          command: ["/k8s-secret-restart-controller" "-v=5" "-namespace" "$(POD_NAMESPACE)"]
